import numpy as np
var = np.array([1,2,3,4,5,6,7,8,9])
print("min: ",np.min(var))
print("max: ",np.max(var))
print("argmin: ",np.argmin(var))
print("argmax: ",np.argmax(var))
print("sqrt: ",np.sqrt(var))
print("sin: ",np.sin(var))
print("cos: ",np.cos(var))
print("cumsum: ",np.cumsum(var))

var1 = np.array([[1,2,3,4,5,6,7,8,9],[13,12,15,14,16,11,17,18,19]])
print("min: ",np.min(var1,1))
print("max: ",np.max(var1,1))
print("argmin: ",np.argmin(var1,1))
print("argmax: ",np.argmax(var1,1))
print("sqrt: ",np.sqrt(var1))
print("sin: ",np.sin(var1))
print("cos: ",np.cos(var1))
print("cumsum: ",np.cumsum(var1,0))